---
users:
- username: "francis"
  ssh_pub_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINK7mMVKOmELe+FVvn1oWNRwKiANgTwcnzte3vWK3nMV"
  shell: "/bin/bash"
- username: "deploy"
  ssh_pub_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINK7mMVKOmELe+FVvn1oWNRwKiANgTwcnzte3vWK3nMV"
  shell: "/bin/bash"
