---
- name: "install packages on the hosts"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "nginx"
    - "keepalived"
    - "python3-psycopg2"
    - "python3-flask"
  notify:
    - "enable nginx"

- name: "nginx | allow http on firewalld"
  ansible.posix.firewalld:
    service: "http"
    permanent: true
    immediate: true
    state: "enabled"
    zone: "{{ item }}"
  with_items:
    - "public"
    - "internal"
    - "trusted"
    - "home"
  notify:
    - "reload firewalld"

- name: "nginx | allow https on firewalld"
  ansible.posix.firewalld:
    service: "http"
    permanent: true
    immediate: true
    state: "enabled"
    zone: "{{ item }}"
  with_items:
    - "public"
    - "internal"
    - "trusted"
    - "home"
  notify:
    - "reload firewalld"

- name: "keepalived | deploy nginx health check"
  ansible.builtin.copy:
    src: "check_nginx.sh"
    dest: "/usr/libexec/keepalived/scripts/check_nginx.sh"
    mode: '0755'
    owner: "keepalived_script"
    group: "keepalived_script"
  notify:
    - "reload keepalived"

- name: "keepalived | template config"
  ansible.builtin.template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    mode: '0644'
  notify:
    - "restart keepalived"
    - "reload keepalived"

- name: "ensure services started"
  ansible.builtin.service:
    name: "{{ item }}"
    state: "started"
  with_items:
    - "nginx"
    - "keepalived"

