---
- name: "add consul gpg key"
  ansible.builtin.rpm_key:
    key: "https://rpm.releases.hashicorp.com/gpg"
    state: "present"

- name: "provide consul through hashicorp repo"
  ansible.builtin.yum_repository:
    name: "hasicorp"
    description: "Hashicorp RPM repo"
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    state: "present"
    enabled: true
    gpgcheck: true

- name: "consul | create consul group"
  ansible.builtin.group:
    name: "consul"
    state: "present"

- name: "consul | create consulql user"
  ansible.builtin.user:
    name: "consul"
    groups: "consul"
    shell: "/bin/false"
    state: "present"
    password: "!"
    create_home: false
    system: true

- name: "install packages on the hosts"
  ansible.builtin.package:
    name: "consul"
    state: "present"
  notify:
    - "enable consul"
    - "start consul"

