---
- name: "add consul gpg key"
  ansible.builtin.rpm_key:
    key: "https://rpm.releases.hashicorp.com/gpg"
    state: "present"

- name: "provide consul through hashicorp repo"
  ansible.builtin.yum_repository:
    name: "hasicorp"
    description: "Hashicorp RPM repo"
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    state: "present"
    enabled: true
    gpgcheck: true

- name: "install packages on the hosts"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "consul"
    - "keepalived"

- name: "ensure services enabled"
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - "consul"
    - "keepalived"

- name: "consul | allow consul on firewalld"
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: "enabled"
  with_items:
    - "8500/tcp"
    - "8501/tcp"
    - "8502/tcp"
    - "8503/tcp"
    - "8300/tcp"
    - "8301/tcp"
    - "8302/tcp"
    - "8600/tcp"
    - "8301/udp"
    - "8302/udp"
    - "8600/udp"
  notify:
    - "reload firewalld"

- name: "keepalived | create keepalived_script group"
  ansible.builtin.group:
    name: "keepalived_script"
    state: "present"
  notify:
    - "reload keepalived"

- name: "keepalived | create keepalived_script user"
  ansible.builtin.user:
    name: "keepalived_script"
    groups: "keepalived_script"
    shell: "/bin/false"
    state: "present"
    password: "!"
    create_home: false
    system: true
  notify:
    - "reload keepalived"

- name: "keepalived | ensure script path"
  ansible.builtin.file:
    dest: "/usr/libexec/keepalived/scripts"
    state: "directory"

- name: "keepalived | template config"
  ansible.builtin.template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    mode: '0644'
  notify:
    - "reload keepalived"

- name: "consul | create consul group"
  ansible.builtin.group:
    name: "consul"
    state: "present"

- name: "consul | create consulql user"
  ansible.builtin.user:
    name: "consul"
    groups: "consul"
    shell: "/bin/false"
    state: "present"
    password: "!"
    create_home: false
    system: true
