---
- name: "install and basics"
  tags: ["base"]
  ansible.builtin.import_tasks:
    file: "base.yaml"

- name: "server setup"
  tags: ["setup", "consul", "server"]
  ansible.builtin.import_tasks:
    file: "server.yaml"
  when: "consul.server"

- name: "agent setup"
  tags: ["setup", "consul", "agent"]
  ansible.builtin.import_tasks:
    file: "agent.yaml"
  when: "not consul.server"
