---
- name: "run common role against all"
  hosts: all
  become: true
  roles:
    - role: "common"
      tags: ["common", "base"]

- name: "setup frontend hosts"
  hosts: frontend
  become: true
  tags: ["frontend", "application"]
  roles:
    - role: "nginx"
      tags: ["nginx", "frontend"]

- name: "setup consul"
  hosts: consul
  become: true
  tags: ["consul", "application"]
  roles:
    - role: "consul"
      tags: ["consul", "backend"]

- name: "setup backend hosts"
  hosts: backend
  become: true
  tags: ["backend", "application"]
  roles:
    - role: "postgres"
      tags: ["postgres", "backend"]
      environment:
        PGDATA: "{{ postgres.data_directory }}"
