---
- name: "Run common role against all"
  hosts: all
  become: true
  roles:
    - role: "common"
      tags: ["common", "base"]

- name: "Setup consul"
  hosts: all
  become: true
  tags: ["consul"]
  roles:
    - role: "consul"

- name: "Setup keepalived"
  hosts: ["frontend", "db", "lb"]
  become: true
  tags: ["keepalived"]
  roles:
    - role: "keepalived"

- name: "Setup frontend hosts"
  hosts: frontend
  become: true
  tags: ["frontend", "application"]
  roles:
    - role: "nginx"
      tags: ["nginx", "frontend"]
    - role: "demo-app"
      tags: ["demo-app", "frontend"]

- name: "Setup database nodes"
  hosts: db
  become: true
  tags: ["db", "application"]
  roles:
    - role: "postgres"
      tags: ["postgres", "db"]
      environment:
        PGDATA: "{{ postgres.data_directory }}"
