---
# consul
- name: "enable consul"
  ansible.builtin.service:
    name: "consul"
    enabled: true
- name: "start consul"
  ansible.builtin.service:
    name: "consul"
    state: "started"
- name: "stop consul"
  ansible.builtin.service:
    name: "consul"
    state: "stopped"
- name: "restart consul"
  ansible.builtin.service:
    name: "consul"
    state: "restarted"
- name: "reload consul"
  ansible.builtin.service:
    name: "consul"
    state: "reloaded"
# firewalld
- name: "start firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "started"
- name: "restart firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "restarted"
- name: "reload firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "reloaded"
