---
# consul
- name: "start consul"
  ansible.builtin.service:
    name: "consul"
    state: "started"
- name: "stop consul"
  ansible.builtin.service:
    name: "consul"
    state: "stopped"
- name: "restart consul"
  ansible.builtin.service:
    name: "consul"
    state: "restarted"
- name: "reload consul"
  ansible.builtin.service:
    name: "consul"
    state: "reloaded"
# firewalld
- name: "start firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "started"
- name: "stop firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "stopped"
- name: "restart firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "restarted"
- name: "reload firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "reloaded"
# keepalived
- name: "start keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "started"
- name: "stop keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "stopped"
- name: "restart keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "restarted"
- name: "reload keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "reloaded"
