---
# nginx
- name: "Enable nginx"
  ansible.builtin.service:
    name: "nginx"
    enabled: true
- name: "Start nginx"
  ansible.builtin.service:
    name: "nginx"
    state: "started"
- name: "Stop nginx"
  ansible.builtin.service:
    name: "nginx"
    state: "stopped"
- name: "Restart nginx"
  ansible.builtin.service:
    name: "nginx"
    state: "restarted"
- name: "Reload nginx"
  ansible.builtin.service:
    name: "nginx"
    state: "reloaded"
# firewalld
- name: "Start firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "started"
- name: "Stop firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "stopped"
- name: "Restart firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "restarted"
- name: "Reload firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "reloaded"
# keepalived
- name: "Start keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "started"
- name: "Stop keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "stopped"
- name: "Restart keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "restarted"
- name: "Reload keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "reloaded"
