---
- name: "reload daemons"
  ansible.builtin.systemd_service:
    daemon_reload: true
# firewalld
- name: "start firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "started"
- name: "stop firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "stopped"
- name: "restart firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "restarted"
- name: "reload firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "reloaded"
# keepalived
- name: "start keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "started"
- name: "stop keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "stopped"
- name: "restart keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "restarted"
- name: "reload keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "reloaded"
# patroni
- name: "start patroni"
  ansible.builtin.service:
    name: "patroni"
    state: "started"
- name: "stop patroni"
  ansible.builtin.service:
    name: "patroni"
    state: "stopped"
- name: "restart patroni"
  ansible.builtin.service:
    name: "patroni"
    state: "restarted"
- name: "reload patroni"
  ansible.builtin.service:
    name: "patroni"
    state: "reloaded"
# consul
- name: "start consul"
  ansible.builtin.service:
    name: "consul"
    state: "started"
- name: "stop consul"
  ansible.builtin.service:
    name: "consul"
    state: "stopped"
- name: "restart consul"
  ansible.builtin.service:
    name: "consul"
    state: "restarted"
- name: "reload consul"
  ansible.builtin.service:
    name: "consul"
    state: "reloaded"
