---
- name: "Reload daemons"
  ansible.builtin.systemd_service:
    daemon_reload: true
# firewalld
- name: "Start firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "started"
- name: "Stop firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "stopped"
- name: "Restart firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "restarted"
- name: "Reload firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "reloaded"
# keepalived
- name: "Start keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "started"
- name: "Stop keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "stopped"
- name: "Restart keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "restarted"
- name: "Reload keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "reloaded"
# patroni
- name: "Enable patroni"
  ansible.builtin.service:
    name: "patroni"
    enabled: true
- name: "Start patroni"
  ansible.builtin.service:
    name: "patroni"
    state: "started"
- name: "Stop patroni"
  ansible.builtin.service:
    name: "patroni"
    state: "stopped"
- name: "Restart patroni"
  ansible.builtin.service:
    name: "patroni"
    state: "restarted"
- name: "Reload patroni"
  ansible.builtin.service:
    name: "patroni"
    state: "reloaded"
