---
# postgresql@{{ ansible.unit_target }}
- name: "start postgresql"
  ansible.builtin.service:
    name: "postgresql-{{ postgres.version }}"
    state: "started"
- name: "stop postgresql"
  ansible.builtin.service:
    name: "postgresql-{{ postgres.version }}"
    state: "stopped"
- name: "restart postgresql"
  ansible.builtin.service:
    name: "postgresql-{{ postgres.version }}"
    state: "restarted"
- name: "reload postgresql"
  ansible.builtin.service:
    name: "postgresql-{{ postgres.version }}"
    state: "reloaded"
# pgbouncer
- name: "start pgbouncer"
  ansible.builtin.service:
    name: "pgbouncer"
    state: "started"
- name: "stop pgbouncer"
  ansible.builtin.service:
    name: "pgbouncer"
    state: "stopped"
- name: "restart pgbouncer"
  ansible.builtin.service:
    name: "pgbouncer"
    state: "restarted"
- name: "reload pgbouncer"
  ansible.builtin.service:
    name: "pgbouncer"
    state: "reloaded"
# firewalld
- name: "start firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "started"
- name: "stop firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "stopped"
- name: "restart firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "restarted"
- name: "reload firewalld"
  ansible.builtin.service:
    name: "firewalld"
    state: "reloaded"
# keepalived
- name: "start keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "started"
- name: "stop keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "stopped"
- name: "restart keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "restarted"
- name: "reload keepalived"
  ansible.builtin.service:
    name: "keepalived"
    state: "reloaded"
# patroni
- name: "start patroni"
  ansible.builtin.service:
    name: "patroni"
    state: "started"
- name: "stop patroni"
  ansible.builtin.service:
    name: "patroni"
    state: "stopped"
- name: "restart patroni"
  ansible.builtin.service:
    name: "patroni"
    state: "restarted"
- name: "reload patroni"
  ansible.builtin.service:
    name: "patroni"
    state: "reloaded"
# consul
- name: "start consul"
  ansible.builtin.service:
    name: "consul"
    state: "started"
- name: "stop consul"
  ansible.builtin.service:
    name: "consul"
    state: "stopped"
- name: "restart consul"
  ansible.builtin.service:
    name: "consul"
    state: "restarted"
- name: "reload consul"
  ansible.builtin.service:
    name: "consul"
    state: "reloaded"
