---
- name: "Yum | update"
  ansible.builtin.dnf:
    update_cache: true

- name: "Install basic packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "openssh-server"
    - "python3"
    - "firewalld"
    - "coreutils"
    - "less"
    - "vim"
    - "man"
    - "epel-release"
  notify:
    - "Enable sshd"
    - "Enable firewalld"

- name: "Sshd | render banner"
  ansible.builtin.template:
    src: "sshd_banner.j2"
    dest: "/etc/ssh/banner"
    owner: "root"
    mode: "0644"
  notify:
    - "Reload sshd"

- name: "Sshd | render config template"
  ansible.builtin.template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: "root"
    mode: "0644"
  notify:
    - "Reload sshd"

- name: "Firewalld | start service"
  ansible.builtin.service:
    name: "firewalld"
    state: "started"

- name: "Firewalld | allow ssh access"
  ansible.posix.firewalld:
    service: "ssh"
    permanent: true
    immediate: true
    state: "enabled"
    zone: "{{ item }}"
  with_items:
    - "public"
    - "internal"
    - "trusted"
    - "home"
  notify:
    - "Reload firewalld"

- name: "Ensure the installed services are running"
  ansible.builtin.service:
    name: "{{ item }}"
    state: "started"
  with_items:
    - "sshd"
    - "firewalld"
