---
- name: "Python3 check and setup"
  tags: ["python"]
  ansible.builtin.import_tasks:
    file: "python.yaml"

- name: "Basic setup"
  tags: ["basic"]
  ansible.builtin.import_tasks:
    file: "basic.yaml"

- name: "User setup"
  tags: ["users"]
  ansible.builtin.import_tasks:
    file: "user.yaml"

- name: "Ensure running service"
  ansible.builtin.service:
    name: "{{ item }}"
    state: "started"
  with_items:
    - "sshd"
    - "firewalld"
