---
- name: "Create admins group"
  ansible.builtin.group:
    name: "admins"
    state: "present"

- name: "Create docker group"
  ansible.builtin.group:
    name: "docker"
    state: "present"
    gid: 1750

- name: "Create admins group in sudoers setup"
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers"
    state: "present"
    regexp: "^%admins"
    line: "%admins ALL=(ALL) NOPASSWD: ALL"

- name: "Create users"
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: "admins"
    shell: "{{ item.shell }}"
    state: "present"
    password: "!"
  with_items: "{{ users }}"

- name: "Add ssh keys of the user"
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.ssh_pub_keys | join('\n') }}"
    exclusive: true
  with_items:
    - "{{ users }}"
