keepalived:
  virtual_router_id: 100
  interface: "eth0"
  advert_int: 4
  priority: 100
  auth_pass: "foo123bar"

postgres:
  version: "17"
  listen_addresses: ["127.0.0.1"]
  port: 5432
  username: "postgres"
  password: "postgres"
  data_directory: "/var/lib/pgsql/17/data"
  home_directory: "/var/lib/pgsql"
  log:
    directory: "/var/log/postgres"
  replication_network: "127.0.0.0/8"
  trusted_network: "127.0.0.0/8"
  replication:
    application_name: "foobar"
    username: "hello"
    password: "world"
  password_encryption: "scram-sha-256"

patroni:
  cluster_name: "foobar"
  port: 8008
  log:
    level: "INFO"
    directory: "/var/log/patroni"
  watchdog:
    mode: "off"

consul:
  port: 8500
  host: "127.0.0.1"
  datacenter: "foo"
  data_dir: "/opt/consul"
  ui:
    enabled: "true"
  client_addr: "127.0.0.1"
  bind_addr: "127.0.0.1"
  retry_join: ["127.0.0.1"]
  log_level: "INFO"
