keepalived:
  virtual_router_id: 100
  interface: "eth0"
  advert_int: 4
  priority: 100
  auth_pass: "foo123bar"

postgres:
  version: "17"
  primary_address: "127.0.0.1"
  listen_addresses: "127.0.0.1"
  port: 5432
  unit_target: "default"
  data_directory: "/var/lib/pgsql/17/data"
  bin_directory: "/usr/pgsql-17/bin/"
  max_connections: 5
  wal:
    level: "replica"
    max_senders: 5
  max_replication_slots: 2
  hot_standby: "on"
  log:
    directory: "/var/log/postgres"
  shared_buffers: "128MB"
  work_mem: "8MB"
  maintenance_work_mem: "64MB"
  effective_cache_size: "256MB"
  archive:
    mode: "off"
    command: ""
  replication_network: "127.0.0.0/8"
  trusted_network: "127.0.0.0/8"
  standby_mode: "off"
  primary_conninfo: "host=127.0.0.1 port=5432 user=rep_user password=rep_pass application_name=standby"
  recovery_target_timeline: "latest"
  replication:
    application_name: "foobar"
    username: "hello"
    password: "world"
  password_encryption: "scram-sha-256"

patroni:
  cluster_name: "foobar"
  port: 8008
  log:
    level: "INFO"

pgbouncer:
  port: 6432

consul:
  port: 8500
  host: "127.0.0.1"
  datacenter: "foo"
  data_dir: "/opt/consul"
  ui:
    enabled: "true"
  client_addr: "127.0.0.1"
  bind_addr: "127.0.0.1"
  retry_join: ["127.0.0.1"]
  log_level: "INFO"
