---
- name: "add postgresql gpg key"
  ansible.builtin.rpm_key:
    key: "https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL"
    state: "present"

- name: "add consul gpg key"
  ansible.builtin.rpm_key:
    key: "https://rpm.releases.hashicorp.com/gpg"
    state: "present"

- name: "provide consul through hashicorp repo"
  ansible.builtin.yum_repository:
    name: "hasicorp"
    description: "Hashicorp RPM repo"
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    state: "present"
    enabled: true
    gpgcheck: true

- name: "add postgresql repository through pacakge"
  ansible.builtin.package:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: "present"

- name: "disable built-in postgresql module"
  ansible.builtin.command: "dnf -qy module disable postgresql"
  changed_when: false

- name: "install packages on the hosts"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "postgresql{{ postgres.version }}-server"
    - "postgresql{{ postgres.version }}-contrib"
    - "patroni"
    - "patroni-consul"
    - "keepalived"
  notify:
    - "enable patroni"
