---
- name: "consul | render agent config"
  ansible.builtin.template:
    src: "consul.hcl.j2"
    dest: "/etc/consul.d/agent.hcl"
    owner: "consul"
    group: "consul"
    mode: '0644'
  notify:
    - "restart consul"
