---
# TODO: need to check how to make this idempotent, but out of scope for the
# moment, data may be loaded duplicate for now. A fix for this would be
# validating the table exists and only loading after that is not the case.
- name: "postgresql | check port"
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ postgres.port }}"
    delay: 2

- name: "patroni | check port"
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ patroni.port }}"
    delay: 2

- name: "patroni | check current status"
  ansible.builtin.command: "/usr/sbin/get-node-role.sh"
  register: "patroni_cmd"

- name: "patroni | set patroni fact"
  ansible.builtin.set_fact:
    patroni: "{{ patroni_cmd.stdout | from_json }}"

- name: "postgresql | copy file to host"
  ansible.builtin.copy:
    src: "{{ item.source }}"
    dest: "/tmp/{{ item.source }}"
    mode: '0755'
  with_items:
    - "{{ postgres.data }}"
  when: 'patroni.Role == "Leader"'

- name: "postgresql | setup table for data"
  community.postgresql.postgresql_table:
    # host: "{{ ansible_host }}"
    name: "{{ item.table }}"
    db: "{{ item.database }}"
    columns: "{{ item.columns }}"
    login_user: "{{ postgres.username }}"
    login_password: "{{ postgres.password }}"
  with_items:
    - "{{ postgres.data }}"
  when: 'patroni.Role == "Leader"'

- name: "postgresql | import data"
  community.postgresql.postgresql_copy:
    # host: "{{ ansible_host }}"
    copy_from: "/tmp/{{ item.source }}"
    db: "{{ item.database }}"
    dst: "{{ item.table }}"
    # TODO: how to make this generic for data imports or just another YAML key
    columns: "data,uitstekend,goed,aanvaardbaar,slecht"
    options:
      format: "csv"
    login_user: "{{ postgres.username }}"
    login_password: "{{ postgres.password }}"
  with_items:
    - "{{ postgres.data }}"
  when: 'patroni.Role == "Leader"'
