---
- name: "Postgresql | check port"
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ postgres.port }}"
    delay: 2
    timeout: 60

- name: "Patroni | check port"
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ patroni.port }}"
    delay: 2
    timeout: 60

- name: "Patroni | check current status"
  ansible.builtin.command: "/usr/sbin/get-node-role.sh"
  register: "patroni_cmd"
  changed_when: false

- name: "Patroni | set patroni fact"
  ansible.builtin.set_fact:
    patroni: "{{ patroni_cmd.stdout | from_json }}"

- name: "Postgresql | setup databases"
  community.postgresql.postgresql_db:
    # host: "{{ ansible_host }}"
    name: "{{ item.name }}"
    login_user: "{{ postgres.username }}"
    login_password: "{{ postgres.password }}"
  with_items: "{{ postgres.databases }}"
  when: 'patroni.Role == "Leader"'
