---
- name: "Keepalived | patroni check script"
  ansible.builtin.template:
    src: "keepalived_patroni_check.sh.j2"
    dest: "/usr/libexec/keepalived/scripts/patroni_check.sh"
    mode: '0755'
    owner: "keepalived_script"
    group: "keepalived_script"

- name: "Keepalived | patroni notify script"
  ansible.builtin.template:
    src: "keepalived_patroni_check.sh.j2"
    dest: "/usr/libexec/keepalived/scripts/patroni_notify.sh"
    mode: '0755'
    owner: "keepalived_script"
    group: "keepalived_script"

- name: "Keepalived | template config"
  ansible.builtin.template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    mode: '0644'
  notify:
    - "Restart keepalived"
    - "Reload keepalived"
