---
- name: "install and basics"
  tags: ["base"]
  ansible.builtin.import_tasks:
    file: "base.yaml"

- name: "primary setup"
  when: "inventory_hostname in groups['db-primary']"
  tags: ["primary"]
  ansible.builtin.import_tasks:
    file: "primary.yaml"

- name: "replica setup"
  when: "inventory_hostname in groups['db-replica']"
  tags: ["replica"]
  ansible.builtin.import_tasks:
    file: "replica.yaml"
