---
- name: "install and basics"
  tags: ["base"]
  ansible.builtin.import_tasks:
    file: "base.yaml"

- name: "postgres"
  tags: ["postgres", "setup"]
  ansible.builtin.import_tasks:
    file: "postgres.yaml"

- name: "keepalived"
  tags: ["keepalived", "setup"]
  ansible.builtin.import_tasks:
    file: "keepalived.yaml"

# when bootstrapping, spin up main instance at first
- name: "patroni-bootstrap"
  when: "inventory_hostname in groups['db-bootstrap']"
  tags: ["patroni", "bootstrap"]
  ansible.builtin.import_tasks:
    file: "patroni.yaml"

# then run against the entire DB cluster
- name: "patroni-cluster"
  tags: ["patroni", "cluster"]
  ansible.builtin.import_tasks:
    file: "patroni.yaml"

- name: "database setup"
  become_user: "postgres"
  tags: ["data", "database"]
  ansible.builtin.import_tasks:
    file: "database.yaml"

- name: "user setup"
  become_user: "postgres"
  tags: ["data", "users"]
  ansible.builtin.import_tasks:
    file: "users.yaml"

- name: "data setup"
  become_user: "postgres"
  tags: ["data"]
  ansible.builtin.import_tasks:
    file: "data.yaml"
