---
- name: "install and basics"
  tags: ["base"]
  ansible.builtin.import_tasks:
    file: "base.yaml"

- name: "primary setup"
  when: "inventory_hostname in groups['db-primary']"
  tags: ["primary"]
  ansible.builtin.import_tasks:
    file: "primary.yaml"

- name: "database setup"
  when: "inventory_hostname in groups['db-primary']"
  become_user: "postgres"
  tags: ["primary", "setup"]
  ansible.builtin.import_tasks:
    file: "database.yaml"

- name: "user setup"
  when: "inventory_hostname in groups['db-primary']"
  become_user: "postgres"
  tags: ["primary", "setup"]
  ansible.builtin.import_tasks:
    file: "users.yaml"

- name: "replica setup"
  when: "inventory_hostname in groups['db-replica']"
  tags: ["replica"]
  ansible.builtin.import_tasks:
    file: "replica.yaml"

# this needs some schema loaded which is out of scope here
- name: "data setup"
  when: "inventory_hostname in groups['db-primary']"
  become_user: "postgres"
  tags: ["setup","data"]
  ansible.builtin.import_tasks:
    file: "data.yaml"
