---
- name: "install and basics"
  tags: ["base"]
  ansible.builtin.import_tasks:
    file: "base.yaml"

# - name: "primary setup"
#   when: "inventory_hostname in groups['db-primary']"
#   tags: ["primary"]
#   ansible.builtin.import_tasks:
#     file: "primary.yaml"

- name: "patroni"
  tags: ["patroni"]
  ansible.builtin.import_tasks:
    file: "patroni.yaml"

# - name: "database setup"
#   become_user: "postgres"
#   tags: ["primary", "setup"]
#   ansible.builtin.import_tasks:
#     file: "database.yaml"
#
# - name: "user setup"
#   become_user: "postgres"
#   tags: ["primary", "setup"]
#   ansible.builtin.import_tasks:
#     file: "users.yaml"
#
# - name: "data setup"
#   when: "inventory_hostname in groups['db-primary']"
#   become_user: "postgres"
#   tags: ["setup","data"]
#   ansible.builtin.import_tasks:
#     file: "data.yaml"

- name: "keepalived"
  tags: ["keepalived"]
  ansible.builtin.import_tasks:
    file: "keepalived.yaml"
